services:
  core-api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "8000:8000"
    restart: always

  automation-worker:
    build:
      context: .
      dockerfile: worker.Dockerfile
    env_file: .env
    restart: always

  frontend:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    restart: always
